[package]
name = "snwf"
version = "0.1.0"
edition = "2021"

[features]
default = ["udt"]
udt = ["dep:tokio-udt"]

[dependencies]
async-trait = "0.1"
derive-new = "0.5"
log = "0.4"
thiserror = "1"
tokio = { version = "1", features = [ "io-std", "io-util", "fs" ] }
tokio-udt = { version = "0.1.0-alpha.8", optional = true }

[dev-dependencies]
assert_fs = "1.0.10"
env_logger = "0.10.0"
file-hashing = "0.1.1"
tokio = { version = "1", features = [ "full" ] }
